language: cpp
os: linux
dist: bionic
compiler:
- gcc
- clang
arch:
- amd64
- arm64
- ppc64le
- s390x
jobs:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
  - os: linux
    dist: xenial
    compiler: clang
  - os: osx
    compiler: gcc
  - os: osx
    compiler: clang
install:
- git clone https://github.com/onqtam/doctest.git
- mkdir doctest/build
- cd doctest/build
- cmake -D DOCTEST_WITH_TESTS=OFF -D DOCTEST_WITH_MAIN_IN_STATIC_LIB=OFF -D CMAKE_BUILD_TYPE=Release ..
- sudo make install
- cd $TRAVIS_BUILD_DIR
script:
- mkdir build_debug
- cd build_debug
- cmake -D CMAKE_BUILD_TYPE=Debug ..
- make
- cd tests
- ./tests
- cd $TRAVIS_BUILD_DIR
- mkdir build_release
- cd build_release
- cmake -D CMAKE_BUILD_TYPE=Release ..
- make
- cd tests
- ./tests