image:
- Visual Studio 2019
configuration:
- Release
- Debug
platform:
- x86
- x64
- ARM
- Any CPU
init:
- pwsh: >-
    cmake --version

    msbuild /version
install:
- pwsh: >-
    git clone https://github.com/onqtam/doctest.git

    cd doctest

    mkdir build

    cd build

    cmake -D DOCTEST_WITH_TESTS=OFF -D DOCTEST_WITH_MAIN_IN_STATIC_LIB=OFF -D CMAKE_CONFIGURATION_TYPES=Release -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=$env:APPVEYOR_BUILD_FOLDER/../share ..

    cmake --build . --config Release --target install
build_script:
- pwsh: >-
    cd $env:APPVEYOR_BUILD_FOLDER

    mkdir build

    cd build

    cmake -D CMAKE_CONFIGURATION_TYPES=$env:CONFIGURATION -D CMAKE_BUILD_TYPE=$env:CONFIGURATION -D CMAKE_PREFIX_PATH=$env:APPVEYOR_BUILD_FOLDER/../share ..

    cmake --build . --config $env:CONFIGURATION
test_script:
- cmd: >-
    cd build/tests

    ctest --output-on-failure -C %CONFIGURATION%